IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROVEEDOR]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[PROVEEDOR](
		[Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,				
		[Nombre] [nvarchar](75) NOT NULL,	
		[Direccion] [nvarchar](75) NULL,	
		[Telefono] [nvarchar](25) NULL			
	 CONSTRAINT [PK_PROVEEDOR] PRIMARY KEY CLUSTERED	
	(
		[Id] DESC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
	) ON [PRIMARY]
	

	PRINT N'CREATE TABLE [dbo].[PROVEEDOR]'
END
ELSE
BEGIN
	DROP TABLE [dbo].[PROVEEDOR];

	PRINT N'DROP TABLE [dbo].[PROVEEDOR]'
END