IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[CATEGORIA]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[CATEGORIA](
		[Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,	
		[Nombre] [nvarchar](75) NOT NULL		
	 CONSTRAINT [PK_CATEGORIA] PRIMARY KEY CLUSTERED	
	(
		[Id] DESC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY],
	CONSTRAINT [UNIQUE_CATEGORIA_Nombre] UNIQUE NONCLUSTERED 
	(
		[Nombre] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
	) ON [PRIMARY]

	PRINT N'CREATE TABLE [dbo].[CATEGORIA]'
END
ELSE
BEGIN
	DROP TABLE [dbo].[CATEGORIA];

	PRINT N'DROP TABLE [dbo].[CATEGORIA]'
END