IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INVENTARIO]') AND type in (N'U'))
BEGIN
	CREATE TABLE [dbo].[INVENTARIO](
		[Id] [decimal](18, 0) IDENTITY(1,1) NOT NULL,
		[ProductoId] [decimal] NOT NULL,
		[nomProducto] [nvarchar](75) NOT NULL,			
		[Validacion] [nvarchar](20) NULL,
		[Unidades] [int] NULL,			
	 CONSTRAINT [PK_INVENTARIO] PRIMARY KEY CLUSTERED	
	(
		[Id] DESC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
	) ON [PRIMARY]
	
	ALTER TABLE [dbo].[INVENTARIO]  WITH CHECK ADD  CONSTRAINT [FK_INVENTARIO_ProductoId] FOREIGN KEY([ProductoId])
	REFERENCES [dbo].[PRODUCTO] ([Id])

	PRINT N'CREATE TABLE [dbo].[INVENTARIO]'
END
ELSE
BEGIN
	DROP TABLE [dbo].[INVENTARIO];

	PRINT N'DROP TABLE [dbo].[INVENTARIO]'
END